#define macros
CFLAGS			= /c /std:c++14 /EHsc

DIR_SRC = .\src
DIR_INC = .\include
DIR_BIN = .\bin
OBJECTS = $(DIR_BIN)\test.obj
EXECUTABLE = $(DIR_BIN)\test.exe

$(DIR_BIN)\test.obj: $(DIR_SRC)\test.cpp
	cl $(CFLAGS) /Fo:$(DIR_BIN)\test.obj /I$(DIR_INC) -c $(DIR_SRC)\test.cpp

$(EXECUTABLE) : $(OBJECTS)
	link /MACHINE:x64 /out:$(EXECUTABLE) $(OBJECTS)

clean:
	del $(DIR_BIN)\*.obj
	del $(EXECUTABLE)

all: $(EXECUTABLE)
	
run:
	$(EXECUTABLE)
